version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: petdb
    ports:
      - "30505:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./data-init:/docker-entrypoint-initdb.d
    networks:
      - backend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "20505:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: rootpassword
      DB_NAME: petdb
    depends_on:
      db:
        condition: service_started
    networks:
      - backend

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: website
    restart: always
    ports:
      - "10505:3000"
    environment:
      NODE_ENV: development
      API_URL: http://api:3001
    depends_on:
      api:
        condition: service_started
    networks:
      - backend

networks:
  backend:
    driver: bridge
