services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./data-init:/docker-entrypoint-initdb.d
    networks:
      - backend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: 5432
    expose:
      - "3001"
    depends_on:
      db:
        condition: service_started
    networks:
      - backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.api.rule=PathPrefix(`/s65114540505/api`)'
      - 'traefik.http.routers.api.entrypoints=web'
      - 'traefik.http.routers.api.priority=200'
      - 'traefik.http.routers.api.middlewares=api-strip-prefix'
      - 'traefik.http.services.api.loadbalancer.server.port=3001'
      - 'traefik.http.middlewares.api-strip-prefix.stripPrefix.prefixes=/s65114540505'

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: website
    restart: always
    environment:
      NODE_ENV: development
      NEXT_PUBLIC_API_BASE_URL: /s65114540505/api
    expose:
      - "3000"
    depends_on:
      api:
        condition: service_started
    networks:
      - backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.website.rule=PathPrefix(`/s65114540505`)'
      - 'traefik.http.routers.website.entrypoints=web'
      - 'traefik.http.routers.website.priority=100'
      - 'traefik.http.routers.website.middlewares=ensure-trailing-slash'
      - 'traefik.http.services.website.loadbalancer.server.port=3000'
      - 'traefik.http.middlewares.ensure-trailing-slash.redirectRegex.regex=^/s65114540505$'
      - 'traefik.http.middlewares.ensure-trailing-slash.redirectRegex.replacement=/s65114540505/'
      - 'traefik.http.middlewares.ensure-trailing-slash.redirectRegex.permanent=true'

  traefik:
    image: traefik:3.0
    container_name: traefik
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./traefix/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./traefix/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - website
      - api
    networks:
      - backend
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.website-root.rule=PathPrefix(`/`)'
      - 'traefik.http.routers.website-root.entrypoints=web'
      - 'traefik.http.routers.website-root.priority=10'
      - 'traefik.http.routers.website-root.middlewares=add-base-prefix'
      - 'traefik.http.routers.website-root.service=website'
      - 'traefik.http.middlewares.add-base-prefix.addPrefix.prefix=/s65114540505'

networks:
  backend:
    driver: bridge
