version: '3.9'

services:
  db:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./data-init:/docker-entrypoint-initdb.d
    networks:
      - backend

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    ports:
      - "${API_PORT}:3001"
    environment:
      NODE_ENV: development
      PORT: ${API_PORT}
      DB_HOST: db
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
    depends_on:
      db:
        condition: service_started
    networks:
      - backend

  website:
    build:
      context: ./website
      dockerfile: Dockerfile
    container_name: website
    restart: always
    ports:
      - "${WEB_PORT}:3000"
    environment:
      NODE_ENV: development
      API_URL: http://api:${API_PORT}
    depends_on:
      api:
        condition: service_started
    networks:
      - backend

networks:
  backend:
    driver: bridge
